# Derivative of Matrix

## import library

In [151]:
import numpy as np
import matplotlib.image as img
import matplotlib.pyplot as plt
import matplotlib.colors as colors

## load image 

In [152]:
I = img.imread('example.jpg')  
print(I)

[[[ 79 124 166]
  [ 77 122 164]
  [ 74 118 163]
  ...
  [ 19  64 106]
  [ 22  67 109]
  [ 22  69 113]]

 [[ 73 118 160]
  [ 72 117 159]
  [ 70 115 157]
  ...
  [ 24  69 111]
  [ 24  71 113]
  [ 26  73 117]]

 [[ 68 113 155]
  [ 67 112 154]
  [ 64 111 153]
  ...
  [ 26  73 115]
  [ 28  75 119]
  [ 29  78 121]]

 ...

 [[ 37  95 145]
  [ 37  95 145]
  [ 38  96 146]
  ...
  [ 38 100 151]
  [ 38 100 151]
  [ 38 100 151]]

 [[ 37  95 145]
  [ 37  95 145]
  [ 37  95 145]
  ...
  [ 38 100 151]
  [ 38 100 151]
  [ 38 100 151]]

 [[ 37  95 145]
  [ 37  95 145]
  [ 37  95 145]
  ...
  [ 38 100 151]
  [ 38 100 151]
  [ 38 100 151]]]


## check the size of image

In [153]:
n_row = I.shape[0]
n_col = I.shape[1]
print(I.shape[2])
print(I.shape)

3
(453, 680, 3)


## convert the input image into gray scale if it is color

In [154]:
if I.shape[2] == 3:
    red = I[:,:,0]
    blue = I[:,:,1]
    green = I[:,:,2]
    I = 0.2126 * red + 0.7152 * blue + 0.0722 * green


## normalize input image so that the range of image is $[0, 1]$

In [155]:
I = I / 255.0


```git commit -a -m "load image" ``` \
```git push origin master```

## generate a matrix to compute the derivative in $x$-direction

In [156]:
Dx = 


SyntaxError: invalid syntax (<ipython-input-156-ed60e25ca172>, line 1)

## compute the derivative of $I$ with respect to $x$-direction

In [ ]:
Ix = 

```git commit -a -m "compute the derivative in x-direction"``` \
```git push origin master```

## generate a matrix to compute the derivative in $y$-direction

In [ ]:
Dy = 


## compute the derivative of $I$ with respect to $y$-direction

In [ ]:
Iy = 

```git commit -a -m "compute the derivative in y-direction"``` \
```git push origin master```

## compute $L_2^2$ of the gradient of $I$

In [ ]:
norm_gradient = 

## define functions for the visualization

In [ ]:
def plot_image(I):
    
    plt.figure(figsize=(10,10))
    plt.imshow( , , )
    plt.title('input image')
    plt.axis('off')
        
def plot_image_derivative_x(Ix):
    
    plt.figure(figsize=(10,10))
    plt.imshow( , , )
    plt.title('image derivative of x')
    plt.axis('off')

    
def plot_image_derivative_y(Iy):
    
    plt.figure(figsize=(10,10))
    plt.imshow( , , )
    plt.title('image derivative of y')
    plt.axis('off')

    
def plot_norm_gradient(norm_gradient):

    plt.figure(figsize=(10,10))
    plt.imshow( , , )
    plt.title('norm gradient')
    plt.axis('off')

```git commit -a -m "define functions for the visualization"``` \
```git push origin master```

# ###################################################################

# # results

# ###################################################################

# # 01. plot the input image in gray scale

In [ ]:
plot_image(I)

# # 02. plot the derivative $I_x$ of input image in x-direction

In [ ]:
plot_image_derivative_x(Ix)

# # 03. plot the derivative $I_y$ of input image in y-direction

In [ ]:
plot_image_derivative_y(Iy)

# # 04. plot $L_2^2$ norm $I_x^2 + I_y^2$ of the gradient of input image

In [ ]:
plot_norm_gradient(norm_gradient)